apiVersion: v1
kind: ConfigMap
metadata:
  name: rtrwnet-config
data:
  SERVER_PORT: "8089"
  SERVER_HOST: "0.0.0.0"
  GIN_MODE: "release"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_USER: "postgres"
  DB_NAME: "rtrwnet_saas"
  DB_SSLMODE: "disable"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  ENABLE_RADIUS: "true"
  RADIUS_AUTH_PORT: "1812"
  RADIUS_ACCT_PORT: "1813"
  CORS_ALLOWED_ORIGINS: "https://fureup.my.id,https://app.fureup.my.id,https://admin.fureup.my.id"
