apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rtrwnet-prod

resources:
  - ../../base
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml

patches:
  - path: backend-patch.yaml
    target:
      kind: Deployment
      name: backend
  - path: freeradius-patch.yaml
    target:
      kind: Deployment
      name: freeradius
  - path: openvpn-patch.yaml
    target:
      kind: Deployment
      name: openvpn

images:
  - name: davaputra/rtrwnet-backend
    newTag: latest
  - name: davaputra/rtrwnet-user-dashboard
    newTag: latest
  - name: davaputra/rtrwnet-admin-dashboard
    newTag: latest
  - name: davaputra/rtrwnet-homepage
    newTag: latest
  - name: davaputra/rtrwnet-freeradius
    newTag: latest

replicas:
  - name: backend
    count: 2
  - name: freeradius
    count: 2
  - name: openvpn
    count: 1
