apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rtrwnet-prod

bases:
  - ../../base

resources:
  - configmap.yaml
  - secrets.yaml

patchesStrategicMerge:
  - backend-patch.yaml
  - freeradius-patch.yaml
  - openvpn-patch.yaml

images:
  - name: davaputra/rtrwnet-backend
    newTag: latest
  - name: davaputra/rtrwnet-user-dashboard
    newTag: latest
  - name: davaputra/rtrwnet-admin-dashboard
    newTag: latest
  - name: davaputra/rtrwnet-homepage
    newTag: latest
  - name: davaputra/rtrwnet-freeradius
    newTag: latest

replicas:
  - name: backend
    count: 2
  - name: freeradius
    count: 2
  - name: openvpn
    count: 1
