apiVersion: v1
kind: Secret
metadata:
  name: rtrwnet-secrets
type: Opaque
stringData:
  # PENTING: Ganti dengan nilai production yang sebenarnya!
  DB_PASSWORD: "CHANGE_ME_PRODUCTION_PASSWORD"
  JWT_SECRET: "CHANGE_ME_PRODUCTION_JWT_SECRET_MIN_32_CHARS"
  MIDTRANS_SERVER_KEY: "Mid-server-xxx"
  MIDTRANS_CLIENT_KEY: "Mid-client-xxx"
  SMTP_PASSWORD: ""
