apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend.yaml
  - frontend-admin.yaml
  - frontend-homepage.yaml
  - frontend-user.yaml
  - postgres.yaml
  - postgres-init-configmap.yaml
  - redis.yaml

commonLabels:
  app: rtrwnet
