apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - postgres-deployment.yaml
  - redis-deployment.yaml
  - backend-deployment.yaml
  - frontend-user-deployment.yaml
  - frontend-admin-deployment.yaml
  - frontend-homepage-deployment.yaml
  - freeradius-deployment.yaml
  - openvpn-deployment.yaml
  - postgres-init-configmap.yaml

configMapGenerator:
  - name: app-config
    literals:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=rtrwnet_saas
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SERVER_PORT=8089
      - GIN_MODE=release

secretGenerator:
  - name: app-secrets
    literals:
      - DB_USER=postgres
      - DB_PASSWORD=changeme
      - JWT_SECRET=changeme
