apiVersion: v1
kind: ConfigMap
metadata:
  name: rtrwnet-config
data:
  SERVER_PORT: "8089"
  SERVER_HOST: "0.0.0.0"
  GIN_MODE: "release"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_USER: "postgres"
  DB_NAME: "rtrwnet_saas"
  DB_SSLMODE: "disable"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  ENABLE_RADIUS: "true"
  RADIUS_AUTH_PORT: "1812"
  RADIUS_ACCT_PORT: "1813"
  CORS_ALLOWED_ORIGINS: "https://staging.fureup.my.id,https://app-staging.fureup.my.id,https://admin-staging.fureup.my.id"
  # SMTP
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"
  SMTP_USERNAME: "davput36@gmail.com"
  SMTP_FROM: "davput36@gmail.com"
  # Midtrans
  MIDTRANS_IS_PRODUCTION: "false"
  # Cloudflare R2
  R2_ACCOUNT_ID: "3fc6c8530bfd214b02b0f4ebceffce59"
  R2_BUCKET_NAME: "websass"
  R2_PUBLIC_URL: "https://pub-d96bc6b2ab634a15b29c8083a2e7eb5b.r2.dev"
  # VPN
  VPN_SERVER_IP: "202.10.48.155"
