apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rtrwnet-staging

resources:
  - ../../base
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - ingress.yaml

commonLabels:
  env: staging
