apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rtrwnet-staging

resources:
  - ../../base
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - ingress.yaml

commonLabels:
  env: staging

images:
  - name: rtrwnet-backend
    newName: ${DOCKER_REGISTRY}/rtrwnet-backend
    newTag: ${IMAGE_TAG}
  - name: rtrwnet-admin-dashboard
    newName: ${DOCKER_REGISTRY}/rtrwnet-admin-dashboard
    newTag: ${IMAGE_TAG}
  - name: rtrwnet-user-dashboard
    newName: ${DOCKER_REGISTRY}/rtrwnet-user-dashboard
    newTag: ${IMAGE_TAG}
  - name: rtrwnet-homepage
    newName: ${DOCKER_REGISTRY}/rtrwnet-homepage
    newTag: ${IMAGE_TAG}
