apiVersion: v1
kind: Secret
metadata:
  name: rtrwnet-secrets
type: Opaque
stringData:
  DB_PASSWORD: "cvkcvk12"
  JWT_SECRET: "your-super-secret-jwt-key-change-in-production-min-32-chars"
  MIDTRANS_SERVER_KEY: "SB-Mid-server-Fz1hvChGfUryoGGPSKWPo1sf"
  MIDTRANS_CLIENT_KEY: "SB-Mid-client-mdWVbehXnLBDR0mn"
  SMTP_PASSWORD: "vunc dwzp eetg kgfo"
  R2_ACCESS_KEY_ID: "21f9c72202c82c691d913a0a6f13005e"
  R2_ACCESS_KEY_SECRET: "8ce8d06a8e7c78c6e668dbbfe54d6ce04dd955f410d4258c6f68440de8d86316"
