apiVersion: v1
kind: Secret
metadata:
  name: rtrwnet-secrets
type: Opaque
stringData:
  DB_PASSWORD: "cvkcvk12"
  JWT_SECRET: "your-super-secret-jwt-key-change-in-production-min-32-chars"
  MIDTRANS_SERVER_KEY: "SB-Mid-server-xxx"
  MIDTRANS_CLIENT_KEY: "SB-Mid-client-xxx"
  SMTP_PASSWORD: ""
